services:
  mongodb:
    image: mongo:7.0
    container_name: bd_mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - bd_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bd_fastapi_backend
    restart: always
    ports:
      - "8001:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=bd_dashboard_db
    depends_on:
      - mongodb
    networks:
      - bd_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: bd_react_frontend
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - backend
    networks:
      - bd_network

volumes:
  mongo_data:

networks:
  bd_network:
    driver: bridge
